name: CI-WORKFLOW
on:
  push:
    branches: [ "master", "main", "dev" ]
  workflow_dispatch: 

jobs:
  build-test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'  
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20, 22]
        exclude:
          - os: windows-latest
            node-version: 22
    
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Cache Dependencies 
        uses: actions/cache@v5 
        with: 
          path: ~/.npm 
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }} 
          restore-keys: | 
             ${{ runner.os }}-node-${{ matrix.node-version }}-


      - name: build
        run: npm install

      - name: test
        run: npm test
        
      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-1
          path: |
             package*

      - name: deploy
        if: success()
        run: echo "my code is deployed"

      - name: rollback
        if: failure()
        run: echo "rollback is done"
